version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "gasolinerajsm/backend-team"
    assignees:
      - "gasolinerajsm/backend-team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "org.springframework.boot"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin.*"
        update-types: ["version-update:semver-major"]

  # NPM dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "gasolinerajsm/frontend-team"
    assignees:
      - "gasolinerajsm/frontend-team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore major version updates for React and Next.js
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gasolinerajsm/devops-team"
    assignees:
      - "gasolinerajsm/devops-team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gasolinerajsm/devops-team"
    assignees:
      - "gasolinerajsm/devops-team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"