filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/*.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    logtype: gasolinera-app
  fields_under_root: true
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after

- type: docker
  enabled: true
  containers.ids:
    - "*"
  containers.path: "/var/lib/docker/containers"
  containers.stream: "all"
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    logtype: gasolinera-docker
  fields_under_root: true

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- add_host_metadata:
    when.not.contains.tags: forwarded

- decode_json_fields:
    fields: ["message"]
    target: ""
    overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644