http.host: "0.0.0.0"
xpack.monitoring.enabled: false
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
log.level: info
config.reload.automatic: true
config.reload.interval: 3s